version: "3.7"

services:
  caddy:
    container_name: humanbios-server
    image: humanbios-server
    restart: unless-stopped
    volumes:
    - ./log:/app/log
    - ./archive:/usr/src/app/archive
    - ./models:/usr/src/app/models

networks:
  default:
    external:
      name: caddynet
