version: "3.7"

services:
  dynamodb:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    restart: unless-stopped
    ports:
     - 8000:8000

networks:
  default:
    external:
      name: caddynet